name: macOS Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install ncurses

    - name: Build
      run: |
        gcc -o text_editor viva.c -lncurses

    - name: Run Test
      run: |
        ./text_editor --test
         echo "Exit code: $?"

    - name: Check Exit Status
      run: |
        echo "Program exited successfully."
