name: macOS Build and Test

on:
  push:
    branches: [ main ]  # 브랜치 이름을 실제 브랜치로 수정하세요.
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install ncurses
      run: |
        brew install ncurses

    - name: Build
      run: |
        gcc -o text_editor viva.c -lncurses

    - name: Run Test
      run: |
        ./text_editor --test

    - name: Check Exit Status
      run: |
        echo "Program exited successfully."
